server:
  port: 8080
  host: "0.0.0.0"

kafka:
  brokers:
    - "localhost:9092"
  security_protocol: "PLAINTEXT"
  group_id: "default-group"
  topics:
    order_created: "order.created"
    order_confirmed: "order.confirmed"
    inventory_reserved: "inventory.reserved"

logger:
  level: "info"
  encoding: "console"  # Use "json" for production
  output_path: "stdout"
